# Generated by Django 5.2.3 on 2026-02-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
